services:
  blink:
    image: "blink:latest"
    restart: always
    ports:
      - "3000:80"
    build: .

networks:
  default:
    name: blink-network
    ipam:
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.0.0.0/29
          gateway: 10.0.0.1